### ISSUE TITLE
'cloudinary_upload' undefined error

### ISSUE THREAD

**Issue by wiseworksSteve** [Lepozepo/cloudinary#12]
This may be noob problem but I can't get this package to work.

I followed the readme, and things appear to work on the client side. But when it tries to call the server method - I've tried both 'cloudinary_upload' and 'cloudinary_upload_stream' - the server throws an error: Exception while invoking method 'cloudinary_upload' undefined

The method is clearly defined in the server.js file. I've verified that the package is installed. I have no idea why meteor can't seem to find this method, and worse, I have no idea how to troubleshoot it.

**Comment by fabyeah** [comment]
I would like to upload files from the server, but it's not possilble, because server.js is not loaded in package.js. Is that right? Or am I missing something?

**Comment by Lepozepo** [comment]
Uploading from the server is more complex than uploading from the client. A previous version of this package used server uploads but I decided to remove support for it since it is inefficient for the server to be uploading when the client can do it. Are you trying to upload files that are local to the server?

**Comment by fabyeah** [comment]
Yes, I want to upload files being sent to my app via POST request.

My solution now is to add the cloudinary npm package via meteorhacks-npm. It works because the global variable is named "cloudinary" with a lower case "c". So there is no conflict with the "Cloudinary" from this package.

I think it is useful to have the server upload feature, for cases like this.
